def test_full_end_to_end_autorca_workflow(client):
    # 1. Register Tenant
    tenant_res = client.post("/api/v1/tenants/register?tenant_id=e2e-tenant&name=E2E_Enterprise_Corp&tier=ENTERPRISE")
    assert tenant_res.status_code == 200

    # 2. Authenticate & Create Session
    sess_res = client.post("/api/v1/auth/session?user_id=usr-e2e&email=lead@e2e.com&role=ADMIN&tenant_id=e2e-tenant")
    assert sess_res.status_code == 200
    token = sess_res.json()["token"]
    headers = {"Authorization": f"Bearer {token}"}

    # 3. Report Bug
    bug_payload = {
        "bug_id": "bug-e2e-1",
        "title": "Database Connection Pool Timeout in Payment Handler",
        "description": "High memory consumption and connection timeout when processing batch transactions.",
        "stack_trace": "com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Exception during pool initialization",
        "service_name": "payment-gateway",
        "tenant_id": "e2e-tenant"
    }
    bug_res = client.post("/api/v1/bugs/", json=bug_payload)
    assert bug_res.status_code == 200

    # 4. Triage Bug
    triage_res = client.get("/api/v1/bugs/bug-e2e-1/triage")
    assert triage_res.status_code == 200
    assert triage_res.json()["severity"] in ["CRITICAL", "HIGH"]

    # 5. Search KB Context
    kb_res = client.get("/api/v1/kb/search?q=NullPointer")
    assert kb_res.status_code == 200

    # 6. Execute Swarm Analysis
    from app.services.swarm_service import swarm_service
    from app.services.bug_service import bug_service
    bug = bug_service.get_bug("bug-e2e-1")
    swarm_task = swarm_service.create_swarm_task(bug)
    completed_task = swarm_service.execute_swarm(swarm_task.task_id)
    assert completed_task.status.value == "COMPLETED"

    # 7. Sandbox Execution Verification
    sandbox_req = {
        "command": "python -m pytest tests/test_bugs.py",
        "working_directory": "/sandbox",
        "tenant_id": "e2e-tenant"
    }
    sb_res = client.post("/api/v1/sandbox/execute", json=sandbox_req)
    assert sb_res.status_code == 200
    assert sb_res.json()["success"] is True

    # 8. Dispatch GitHub PR
    pr_req = {
        "repo": "e2e-org/payment-gateway",
        "base_branch": "main",
        "head_branch": "fix/autorca-hikari-pool-leak",
        "title": "[AutoRCA Fix] Repair Hikari connection pool leak",
        "body": "Automated patch generated by AutoRCA Python Swarm Engine.",
        "patch_code": "hikariConfig.setLeakDetectionThreshold(2000);",
        "tenant_id": "e2e-tenant"
    }
    pr_res = client.post("/api/v1/github/pull-request", json=pr_req)
    assert pr_res.status_code == 200

    # 9. Log Audit Entry
    audit_params = {
        "event_type": "E2E_SWARM_WORKFLOW_SUCCESS",
        "actor": "usr-e2e",
        "tenant_id": "e2e-tenant"
    }
    audit_res = client.post("/api/v1/audit/log", params=audit_params, json={"task_id": completed_task.task_id})
    assert audit_res.status_code == 200
    assert len(audit_res.json()["checksum"]) == 64
