def test_github_pull_request_creation(client):
    payload = {
        "repo": "acme/payments-service",
        "base_branch": "main",
        "head_branch": "fix/autorca-null-check",
        "title": "[AutoRCA Fix] Add missing null check in payments handler",
        "body": "Automated fix patch generated by AutoRCA Swarm.",
        "patch_code": "if (client == null) return null;",
        "tenant_id": "tenant-alpha"
    }
    res = client.post("/api/v1/github/pull-request", json=payload)
    assert res.status_code == 200
    data = res.json()
    assert data["pr_number"] >= 101
    assert "github.com" in data["pr_url"]
    assert data["status"] == "OPEN"
